name: nepali_utils
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: sarbagya <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
